# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2_sig.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QMainWindow, QTextEdit, 
QAction, QFileDialog, QApplication)
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    counter = 0
    counter2 = 0
    counter3 = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1103, 241))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.w1 = PlotWidget(self.scrollAreaWidgetContents)
        self.w1.setObjectName("w1")
        self.w1.plotItem.addLegend()
        self.w1.plotItem.plot(pen='b',name='plot1')
        self.w1.plotItem.showGrid(x=True,y=True)
        self.gridLayout_2.addWidget(self.w1, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.play1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.play1.setObjectName("play1")
        self.horizontalLayout_3.addWidget(self.play1)
        self.pause1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pause1.setObjectName("pause1")
        self.horizontalLayout_3.addWidget(self.pause1)
        self.stop1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.stop1.setObjectName("stop1")
        self.horizontalLayout_3.addWidget(self.stop1)
        self.clear1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.clear1.setObjectName("clear1")
        self.horizontalLayout_3.addWidget(self.clear1)
        self.plus1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.plus1.setObjectName("plus1")
        self.horizontalLayout_3.addWidget(self.plus1)
        self.min1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.min1.setObjectName("min1")
        self.horizontalLayout_3.addWidget(self.min1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1103, 240))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.w3 = PlotWidget(self.scrollAreaWidgetContents_3)
        self.w3.setObjectName("w3")
        self.w3.plotItem.addLegend()
        self.w3.plotItem.plot(pen='r',name='plot2')
        self.w3.plotItem.showGrid(x=True,y=True)
        self.gridLayout_4.addWidget(self.w3, 1, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.play3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.play3.setObjectName("play3")
        self.horizontalLayout_5.addWidget(self.play3)
        self.pause3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pause3.setObjectName("pause3")
        self.horizontalLayout_5.addWidget(self.pause3)
        self.stop3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.stop3.setObjectName("stop3")
        self.horizontalLayout_5.addWidget(self.stop3)
        self.clear3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.clear3.setObjectName("clear3")
        self.horizontalLayout_5.addWidget(self.clear3)
        self.plus3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.plus3.setObjectName("plus3")
        self.horizontalLayout_5.addWidget(self.plus3)
        self.min3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.min3.setObjectName("min3")
        self.horizontalLayout_5.addWidget(self.min3)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 3, 0, 1, 2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1103, 241))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.w2 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.w2.setObjectName("w2")
        self.w2.plotItem.addLegend()
        self.w2.plotItem.plot(pen='g',name='plot3')
        self.w2.plotItem.showGrid(x=True,y=True)
        self.gridLayout_3.addWidget(self.w2, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.play2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.play2.setObjectName("play2")
        self.horizontalLayout_4.addWidget(self.play2)
        self.pause2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pause2.setObjectName("pause2")
        self.horizontalLayout_4.addWidget(self.pause2)
        self.stop2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.stop2.setObjectName("stop2")
        self.horizontalLayout_4.addWidget(self.stop2)
        self.clear2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.clear2.setObjectName("clear2")
        self.horizontalLayout_4.addWidget(self.clear2)
        self.plus2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.plus2.setObjectName("plus2")
        self.horizontalLayout_4.addWidget(self.plus2)
        self.min2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.min2.setObjectName("min2")
        self.horizontalLayout_4.addWidget(self.min2)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # self.actionOpen = QtWidgets.QAction(MainWindow)
        # self.actionOpen.setObjectName("actionOpen")
        # self.menuFile.addAction(self.actionOpen)
        # self.menubar.addAction(self.menuFile.menuAction())

        self.play1.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\resume.png")) 
        self.stop1.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\stop.png")) 
        self.pause1.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\pause1.png"))
        self.plus1.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\plus.jfif")) 
        self.min1.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\minus.jfif")) 
        self.play1.setIconSize(QtCore.QSize(25,25))
        self.stop1.setIconSize(QtCore.QSize(25,25))
        self.pause1.setIconSize(QtCore.QSize(25,25))
        self.plus1.setIconSize(QtCore.QSize(25,25))
        self.min1.setIconSize(QtCore.QSize(25,25))
        self.play2.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\resume.png")) 
        self.stop2.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\stop.png")) 
        self.pause2.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\pause1.png"))
        self.plus2.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\plus.jfif")) 
        self.min2.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\minus.jfif")) 
        self.play2.setIconSize(QtCore.QSize(25,25))
        self.stop2.setIconSize(QtCore.QSize(25,25))
        self.pause2.setIconSize(QtCore.QSize(25,25))
        self.plus2.setIconSize(QtCore.QSize(25,25))
        self.min2.setIconSize(QtCore.QSize(25,25))
        self.play3.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\resume.png")) 
        self.stop3.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\stop.png")) 
        self.pause3.setIcon(QtGui.QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\pause1.png"))
        self.plus3.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\plus.jfif")) 
        self.min3.setIcon(QIcon("C:\\Users\\Al-Motasem\\OneDrive\\Desktop\\Python\\DSP\\images\\minus.jfif")) 
        self.play3.setIconSize(QtCore.QSize(25,25))
        self.stop3.setIconSize(QtCore.QSize(25,25))
        self.pause3.setIconSize(QtCore.QSize(25,25))
        self.plus3.setIconSize(QtCore.QSize(25,25))
        self.min3.setIconSize(QtCore.QSize(25,25))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play1.setText(_translate("MainWindow", "Play/Resume"))
        self.pause1.setText(_translate("MainWindow", "Pause"))
        self.stop1.setText(_translate("MainWindow", "Stop"))
        self.clear1.setText(_translate("MainWindow", "Open File"))
        self.play3.setText(_translate("MainWindow", "Play/Resume"))
        self.pause3.setText(_translate("MainWindow", "Pause"))
        self.stop3.setText(_translate("MainWindow", "Stop"))
        self.clear3.setText(_translate("MainWindow", "Open File"))
        self.play2.setText(_translate("MainWindow", "Play/Resume"))
        self.pause2.setText(_translate("MainWindow", "Pause"))
        self.stop2.setText(_translate("MainWindow", "Stop"))
        self.clear2.setText(_translate("MainWindow", "Open File"))
        self.plus1.setText(_translate("MainWindow", "Zoom In"))
        self.min1.setText(_translate("MainWindow", "Zoom Out"))
        self.plus2.setText(_translate("MainWindow", "Zoom In"))
        self.min2.setText(_translate("MainWindow", "Zoom Out"))
        self.plus3.setText(_translate("MainWindow", "Zoom In"))
        self.min3.setText(_translate("MainWindow", "Zoom Out"))



from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
